### ISSUE TITLE
Django error on drag and drop

### ISSUE THREAD

**Issue by Fryyyyy** [iambrandontaylor/django-admin-sortable#160] opened 2016-11-30 05:08 UTC
I receive an error when attempting to drag and drop rows in a SortableTabularInline:

```Internal Server Error: /admin/app/event/sort/do-sorting/35/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/adminsortable/admin.py", line 301, in do_sorting_view
    obj.save()
  File "/usr/local/lib/python2.7/dist-packages/adminsortable/models.py", line 101, in save
    super(SortableMixin, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 889, in _save_table
    forced_update)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 939, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 654, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1148, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 824, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1112, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 755, in get_db_prep_save
    prepared=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 747, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1832, in get_prep_value
    return int(value)
TypeError: int() argument must be a string or a number, not 'PositiveIntegerField'
[30/Nov/2016 04:37:08] "POST /admin/app/event/sort/do-sorting/35/ HTTP/1.1" 500 17037
```

The model contains `order_field = models.PositiveIntegerField(default=0, editable=False, db_index=True)` and we're using PostgreSQL.

Cheers!

**Comment by alsoicode** [comment] 2016-11-30 11:21
Which version are you using?

**Comment by alsoicode** [comment] 2016-11-30 11:44
If you look in the `sample_project`, there is a [SortableTabularInline](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/sample_project/app/admin.py#L55) for the [Credit](https://github.com/iambrandontaylor/django-admin-sortable/blob/master/sample_project/app/models.py#L62) model that uses a `PositiveIntegerField` to hold the ordering value.

This model and sorting are working for me. Can you please confirm?

**Comment by Fryyyyy** [comment] 2016-11-30 22:57
Installed from pip - 2.0.21.
The sample project seems to work.

Here's the model (field names, etc redacted)
```
class p(SortableMixin):
    class Meta:
        ordering = ['order_field']

    e = models.ForeignKey(e)
    r = models.ManyToManyField(r, blank=True)
    i = models.ManyToManyField(f, blank=True)
    o = models.CharField(choices=o_choices, max_length=11)
    c = models.TextField(blank=True)
    ou = models.ManyToManyField(f, blank=True)

    order_field = models.PositiveIntegerField(default=0, editable=False, db_index=True)
```

**Comment by alsoicode** [comment] 2016-12-01 00:37
Your model definition looks correct, could you please share your admin class?

**Comment by Fryyyyy** [comment] 2016-12-01 00:38
```
class pInline(SortableTabularInline):
    model = p
    extra = 1
```

and the parent:
```
class eAdmin(MarkdownAdmin):
    list_filter = ('g',)
    inlines = [
        esInline,
        reInline,
        pInline,
    ]
admin.site.register(e, eAdmin)
```

**Comment by alsoicode** [comment] 2016-12-01 00:43
You'll also need your `eAdmin` class to inherit `SortableAdmin`. That's the class that wires up all of the views that django-admin-sortable uses.

**Comment by Fryyyyy** [comment] 2016-12-01 00:44
I have:

```class MarkdownAdmin(NonSortableParentAdmin, admin.ModelAdmin):```

Would that not do it?

**Comment by alsoicode** [comment] 2016-12-01 01:04
That should work. Let me modify the sample project to add a SortableTabularInline to a NonSortableParentAdmin and see if I can reproduce the error.

**Comment by alsoicode** [comment] 2016-12-01 01:11
In the sample project, I switched the inline class for `SortableCategoryWidgetInline` to `SortableTabularInline` and it works as expected. Your `MarkdownAdmin` should only have to inherit `NonSortableParentAdmin` as it eventually inherits `ModelAdmin` up the chain.

**Comment by Fryyyyy** [comment] 2016-12-01 01:12
I changed MarkdownAdmin to just inherit from NonSortableParentAdmin and receive the same error :(

**Comment by alsoicode** [comment] 2016-12-01 01:35
Hmm. I took at look at:

> File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1832, in get_prep_value
    return int(value)
TypeError: int() argument must be a string or a number, not 'PositiveIntegerField'

just to see what `value` ends up being in relation to the model, and it appears to be the primary key of the sorted model. When I `print` the value out on a drag and drop action. For some reason, you're getting a class there instead of the primary key value.

Are you doing any overrides when saving those sortable model instances?

**Comment by Fryyyyy** [comment] 2016-12-01 01:47
No, I don't believe so.
Should I scatter some prints in there?

**Comment by alsoicode** [comment] 2016-12-01 01:53
Wouldn't hurt. Without seeing the exact implementation, it's hard to tell what's going wrong when the model is saved. All I can tell you right now is that the sample code works, which of course isn't helping you :)

**Comment by Fryyyyy** [comment] 2016-12-01 03:04
I put in some prints, and the problem fixed itself.  I took the prints out and it broke again 👊 
Adding things back in one by one to see why my life is so difficult

**Comment by Fryyyyy** [comment] 2016-12-01 03:53
I think this is the problem:
```
>>> from caps_app.models import p
>>> p_obj = p.objects.get(pk=1)
>>> getattr(p_obj, 'order_field')
<django.db.models.fields.PositiveIntegerField: order_field>
```

In adminsortable/admin.py, in do_sorting_view, it uses getattr to get the value of the field (on line 295), and instead of a number receives that object reference, then tries to set it on line 300 and we break in the call to save() on 301.

**Comment by alsoicode** [comment] 2016-12-01 11:13
That's very strange. I'm not seeing that behavior at all. What version of Python and Django are you using and on what OS? My test coverage uses Python 2.7, 3.4 and 3.5 and goes all the way back to Django 1.6.7, and I'm not seeing any failures in that particular area.

I work on Windows 10, but all of the tests are executed in Linux.

**Comment by Fryyyyy** [comment] 2016-12-01 23:29
:~$ python --version
Python 2.7.6

:~$ pip show django
---
Name: Django
Version: 1.10.3
Location: /usr/local/lib/python2.7/dist-packages

**Comment by alsoicode** [comment] 2016-12-02 01:30
I'm running Python 2.7.12 and installed Django 1.10.3 into a virtualenv to run the sample project from, and I still can't reproduce the error you're getting.

**Comment by Fryyyyy** [comment] 2016-12-02 02:07
Maybe it's a Postgres thing?

**Comment by alsoicode** [comment] 2016-12-02 02:10
Hmm. I don't think so. I've run adminsortable against MySQL, Postgres and SQLite without seeing this particular error, and the project has been around since 2011. I've just never seen `getattr` return a class instead of the attribute of the object that you're trying to retrieve.

**Comment by Fryyyyy** [comment] 2016-12-02 02:12
Well it's not returning an abstract class, I don't think, it's returning an instance of a PositiveIntegerField instead of an 'int'

**Comment by alsoicode** [comment] 2016-12-02 02:14
It *should* be returning the value of that field, not the class instance. If I could reproduce it, I could fix it.

**Comment by Fryyyyy** [comment] 2016-12-02 02:15
Oh I definitely agree with that :)
Happy to do whatever debugging necessary

**Comment by alsoicode** [comment] 2016-12-02 02:16
Unfortunately, I'm out of time for this evening, but PRs are *always* welcome if you have some time to poke around on it.

**Comment by Fryyyyy** [comment] 2016-12-02 02:45
Heh heh heh

From #django:
```
[13:40] <Koterpillar> you can't name it 'order_field'
[13:40] <Koterpillar> https://github.com/iambrandontaylor/django-admin-sortable/blob/master/adminsortable/models.py#L55
```

**Comment by alsoicode** [comment] 2016-12-02 02:47
facepalm. I'll get this into the documentation.

**Comment by Fryyyyy** [comment] 2016-12-02 02:48
Or maybe rename the internal variable, since I would imagine a field used for ordering would pretty commonly be called "order_field"?

**Comment by alsoicode** [comment] 2016-12-02 02:54
I've put a note in the README for now. I'll probably make a new branch and change the field name over the weekend. I'm going to close this issue for now, but I'll get it addressed.

**Closed by alsoicode** 2016-12-02 02:54 UTC
